baseURL: "https://viktree.netlify.app/"
languageCode: en-us

title: viktree

copyright: "Copyright (©) 2021, All rights and reserved Vikram Venkataramanan"
disqusShortname: viktree-netlify-com

pygmentsstyle: bw
pygmentscodefences: true

paginate: 10
summaryLength: 20

favicon: favicon.ico

params:
  subtitle: >-
    Glad you could make it! This is a small corner of the internet that [I am](/about) carving out for
    myself. I [write blog posts](/posts) to clarify my ideas and improve my communication skills.
  social:
    - name: GitHub
      short: gh
      icon: github
      url: "https://github.com/viktree"
      color: "#24292E"
    - name: Twitter
      short: tw
      icon: twitter
      color: "#01579B"
      url: "https://twitter.com/torvikram"
    - name: LinkedIn
      short: ln
      icon: linkedin
      color: "#006064"
    - name: RSS
      short: rss
      icon: rss
      color: "#551f2f"
      url: /index.xml
menu:
  main:
    - name: home
      url: /
      weight: 1
    - name: my writings
      url: /posts
      weight: 2
    - name: about me
      url: /about
      weight: 3
    - name: email
      url: mailto:vikram.venkataramanan@mail.utoronto.ca
      weight: 3
    - name: Résumé
      url: "/assets/pdf/resume.pdf"
      weight: 5
