
backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "static/images"

collections:
  - name: post
    label: Posts
    folder: "content/posts"
    create: true
    fields:
      - name: title
        label: Title
      - label: "Publish this page on"
        name: "date"
        widget: "datetime"
      - name: body
        label: Body
        widget: markdown
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
      - label: "Disqus"
        name: "disqus"
        widget: "boolean"
        default: true